### ISSUE TITLE
Is it possible to compile for Raspberry Pi 5? 

### ISSUE THREAD

**Issue by pablogupi** [DistroAV/DistroAV#987]
I have seen other issues talking about the same thing, but they are old and do not talk about the model 5. I think that in this device the NDI reception can work well. The obs works quite well. 

I have tried to compile with build-linux and I don't know whether to discard it or keep trying to compile it (I am not a C expert).

`pablo@raspberrypi:~/Downloads/obs-ndi $ .github/scripts/build-linux 
   =>   Check Linux build requirements
   =>   Installing obs-studio build dependencies...
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'`

What do you think, would it be possible to create an ARM version for the raspberry pi?

**Comment by pablogupi** [comment]
For example, Dicaffeine  support NDI in RaspberryPi https://github.com/melnijir/Dicaffeine

**Comment by qubitrenegade** [comment]
To get through this error, you just need to install `python3-launchpadlib`

    apt get install python3-launchpadlib -y

I also had to install `libobs-dev`

**Comment by pablogupi** [comment]
I finally managed to compile thanks to your instructions. But the plugin does not start

<img width="297" alt="Screenshot 2024-04-26 at 20 05 22" src="https://github.com/obs-ndi/obs-ndi/assets/634243/b2ed8d19-3989-4fb5-a7e9-8de752091a4b">

```
20:06:03.415: Using EGL/X11
20:06:03.415: Physical Cores: 4, Logical Cores: 4
20:06:03.415: Physical Memory: 8053MB Total, 5752MB Free
20:06:03.415: Kernel Version: Linux 6.1.0-rpi8-rpi-2712
20:06:03.415: Distribution: "Debian GNU/Linux" "12"
20:06:03.415: Desktop Environment: LXDE-pi-wayfire
20:06:03.415: Session Type: wayland
20:06:03.415: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.22.1
20:06:03.416: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
20:06:03.416: Portable mode: false
20:06:03.504: OBS 30.0.0 (linux)
20:06:03.504: ---------------------------------
20:06:03.504: ---------------------------------
20:06:03.504: audio settings reset:
20:06:03.504: 	samples per sec: 48000
20:06:03.504: 	speakers:        2
20:06:03.504: 	max buffering:   960 milliseconds
20:06:03.504: 	buffering type:  dynamically increasing
20:06:03.518: ---------------------------------
20:06:03.518: Initializing OpenGL...
20:06:03.821: Loading up OpenGL on adapter Broadcom V3D 7.1
20:06:03.821: glEnable failed, glGetError returned GL_INVALID_ENUM(0x500)
20:06:03.821: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 23.2.1-1~bpo12+rpt3, shading language 3.30
20:06:03.873: ---------------------------------
20:06:03.874: video settings reset:
20:06:03.874: 	base resolution:   1920x1080
20:06:03.874: 	output resolution: 1280x720
20:06:03.874: 	downscale filter:  Bicubic
20:06:03.874: 	fps:               30/1
20:06:03.874: 	format:            NV12
20:06:03.874: 	YUV mode:          Rec. 709/Partial
20:06:03.874: NV12 texture support not available
20:06:03.874: P010 texture support not available
20:06:03.887: Audio monitoring device:
20:06:03.887: 	name: Default
20:06:03.887: 	id: default
20:06:03.887: ---------------------------------
20:06:03.898: Failed to load 'en-US' text for module: 'decklink-captions.so'
20:06:03.912: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
20:06:03.920: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
20:06:03.920: Failed to initialize module 'decklink.so'
20:06:04.284: [pipewire] Available captures:
20:06:04.284: [pipewire]     - Desktop capture
20:06:04.306: v4l2loopback not installed, virtual camera disabled
20:06:04.321: [obs-browser]: Version 2.22.1
20:06:04.321: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2592+g5fc3b43+chromium-103.0.5060.134 (compiled)
20:06:04.705: VAAPI: Failed to initialize display in vaapi_device_h264_supported
20:06:04.705: FFmpeg VAAPI H264 encoding not supported
20:06:04.705: VAAPI: Failed to initialize display in vaapi_device_hevc_supported
20:06:04.705: FFmpeg VAAPI HEVC encoding not supported
20:06:04.768: Skipping module '/usr//lib/aarch64-linux-gnu/obs-plugins/obs-ndi.so' due to possible import conflicts
20:06:04.818: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.3.3 | RPC Version: 1)
20:06:04.818: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.2 | Qt version (run-time): 6.4.2
20:06:04.818: [obs-websocket] [obs_module_load] Linked ASIO Version: 102201
20:06:04.827: [obs-websocket] [obs_module_load] Module loaded.
20:06:04.871: [vlc-video]: VLC 3.0.20 Vetinari found, VLC video source enabled
20:06:04.871: ---------------------------------
20:06:04.872:   Loaded Modules:
20:06:04.872:     vlc-video.so
20:06:04.872:     text-freetype2.so
20:06:04.872:     rtmp-services.so
20:06:04.872:     obs-x264.so
20:06:04.872:     obs-websocket.so
20:06:04.872:     obs-vst.so
20:06:04.872:     obs-transitions.so
20:06:04.872:     obs-outputs.so
20:06:04.872:     obs-filters.so
20:06:04.872:     obs-ffmpeg.so
20:06:04.872:     obs-browser.so
20:06:04.872:     linux-v4l2.so
20:06:04.872:     linux-pulseaudio.so
20:06:04.872:     linux-pipewire.so
20:06:04.872:     linux-jack.so
20:06:04.872:     linux-capture.so
20:06:04.872:     linux-alsa.so
20:06:04.872:     image-source.so
20:06:04.872:     frontend-tools.so
20:06:04.872:     decklink-output-ui.so
20:06:04.872:     decklink-captions.so
20:06:04.872: ---------------------------------
20:06:04.872: ==== Startup complete ===============================================
20:06:04.934: All scene data cleared
20:06:04.934: ------------------------------------------------
20:06:04.937: pulse-input: Server name: 'pulseaudio 16.1'
20:06:04.938: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
20:06:04.938: pulse-input: Started recording from 'auto_null.monitor' (default)
20:06:04.939: [Loaded global audio device]: 'Desktop Audio'
20:06:04.942: Switched to scene 'Scene'
20:06:04.942: ------------------------------------------------
20:06:04.942: Loaded scenes:
20:06:04.942: - scene 'Scene':
20:06:04.942: ------------------------------------------------
20:06:07.473: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)
20:06:07.473: 
20:06:26.516: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700
```
 Thanks a lot for your job @qubitrenegade

**Comment by paulpv** [comment]
> Skipping module '/usr//lib/aarch64-linux-gnu/obs-plugins/obs-ndi.so' due to possible import conflicts

Interesting

**Comment by RayneYoruka** [comment]
RPi5 builds of this plugin are pretty much a "do at your own risk" so I'll be closing.
